#!/bin/sh
#
# Installer for the scrolling MOTD setup. Copies the main script plus ANSI
# art into system locations and wires it into /etc/profile.d so login shells
# display a random piece at 80 columns (via durdraw when available).

set -eu

SCRIPT_NAME=scrolling-motd
BIN_DEST=${INSTALL_BIN:-/usr/local/bin/${SCRIPT_NAME}}
SHARE_ROOT=${INSTALL_SHARE:-/usr/local/share/${SCRIPT_NAME}}
ART_SRC=${ART_SRC:-ansiart}
ART_DEST=${INSTALL_ART_DIR:-${SHARE_ROOT}/ansiart}
PROFILE_SCRIPT=${INSTALL_PROFILE:-/etc/profile.d/${SCRIPT_NAME}.sh}

# Resolve the directory this installer lives in so we copy the right files.
if script_dir=$(cd -- "$(dirname -- "$0")" 2>/dev/null && pwd); then
    :
else
    echo "Unable to resolve installer directory" >&2
    exit 1
fi

main_src=${script_dir}/scrolling-motd.sh

if [ ! -f "$main_src" ]; then
    echo "Missing ${main_src}" >&2
    exit 1
fi

if [ ! -d "${script_dir}/${ART_SRC}" ]; then
    echo "Missing ANSI art directory '${script_dir}/${ART_SRC}'" >&2
    exit 1
fi

echo "Installing ${SCRIPT_NAME} to ${BIN_DEST}"
install -d -m 755 "$(dirname "$BIN_DEST")"
install -m 755 "$main_src" "$BIN_DEST"

echo "Copying ANSI art to ${ART_DEST}"
install -d -m 755 "$ART_DEST"
# Use rsync when available to preserve timestamps; fall back to cp otherwise.
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "${script_dir}/${ART_SRC}/" "${ART_DEST}/"
else
    # shellcheck disable=SC2035
    rm -rf "${ART_DEST:?}/"* 2>/dev/null || true
    cp -a "${script_dir}/${ART_SRC}/." "$ART_DEST/"
fi

echo "Writing profile hook ${PROFILE_SCRIPT}"
cat >"$PROFILE_SCRIPT" <<EOF
#!/bin/sh
# Auto-generated by ${SCRIPT_NAME}'s install script. Runs the scrolling MOTD.
if [ -x "$BIN_DEST" ]; then
    case \$- in
        *i*)
            ANSI_ART_DIR="$ART_DEST" "$BIN_DEST"
            ;;
    esac
fi
EOF
chmod 755 "$PROFILE_SCRIPT"

echo "All done."
echo "Next login shells will render a random ANSI MOTD. Existing sessions can run:"
echo "  ANSI_ART_DIR=\"$ART_DEST\" $BIN_DEST"
